'use client';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { useCart } from './cart-provider';
import { formatPrice } from './types';

export function CartPage() {
  const { items, hydrated, subtotalPaisa, itemCount, setQuantity, removeItem } = useCart();
  return <main id="main-content" className="shop-page shop-container shop-cart-page"><nav className="shop-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Shopping cart</span></nav><p className="shop-eyebrow">THE NEXT STOP: BETTER PERFORMANCE</p><h1>Your shopping cart<span className="shop-count">{itemCount}</span></h1>{!hydrated ? <p role="status" className="shop-loading">Loading your cart…</p> : !items.length ? <div className="shop-empty"><ShoppingBag size={44}/><h2>Your next journey starts here.</h2><p>Your cart is empty. Explore our range and find your Alpha.</p><Link href="/products" className="shop-button">Explore products <ArrowRight size={18}/></Link></div> : <div className="shop-cart-layout"><div className="shop-cart-list">{items.map(item => <article className="shop-cart-item" key={item.productId}><Link className="shop-cart-image" href={`/products/${item.slug}`}><Image src={item.image} alt={item.name} width={130} height={150}/></Link><div className="shop-cart-item-copy"><h2><Link href={`/products/${item.slug}`}>{item.name}</Link></h2><p>{formatPrice(item.pricePaisa)} each</p><div className="shop-quantity"><button aria-label={`Decrease ${item.name} quantity`} onClick={() => setQuantity(item.productId, item.quantity - 1)}><Minus size={15}/></button><input type="number" min={1} max={Math.min(item.stock, 50)} aria-label={`${item.name} quantity`} value={item.quantity} onChange={event => { const value = Number(event.target.value); if (value > 0) setQuantity(item.productId, value); }}/><button aria-label={`Increase ${item.name} quantity`} disabled={item.quantity >= Math.min(item.stock, 50)} onClick={() => setQuantity(item.productId, item.quantity + 1)}><Plus size={15}/></button></div></div><div className="shop-cart-item-end"><strong>{formatPrice(item.pricePaisa * item.quantity)}</strong><button className="shop-text-button" aria-label={`Remove ${item.name}`} onClick={() => removeItem(item.productId)}><Trash2 size={16}/> Remove</button></div></article>)}<Link className="shop-continue" href="/products">Continue shopping <ArrowRight size={16}/></Link></div><aside className="shop-order-summary"><p className="shop-eyebrow">ALMOST ON YOUR WAY</p><h2>Order summary</h2><div className="shop-total-row"><span>Subtotal ({itemCount} items)</span><strong>{formatPrice(subtotalPaisa)}</strong></div><div className="shop-total-row"><span>Delivery</span><span>At checkout</span></div><p className="shop-summary-note">Have a promo code? Add it at checkout. Final prices and availability are confirmed before you place your order.</p><Link href="/checkout" className="shop-button shop-button-full">Continue to checkout <ArrowRight size={18}/></Link><p className="shop-payment-note">Pay with cash when your order arrives.</p></aside></div>}</main>;
}
