export const fallbackProducts = [
  { id: 'alpha-sl-800', slug: 'alpha-sl-800ml', name: 'Alpha SL', description: 'Everyday engine protection for confident journeys. Choose the grade recommended by your vehicle manufacturer.', category: 'Motorcycle', viscosity: '10W-30', size: '800 ml', pricePaisa: 80000, stock: 0, image: '/images/product-sl.webp', featured: true, active: true, specs: { volume: '800 ml', API: 'SL', JASO: 'MA2', application: '4T motorcycle' } },
  { id: 'alpha-semi-1000', slug: 'alpha-semi-synthetic-1000ml', name: 'Alpha Semi Synthetic', description: 'Semi synthetic engine oil for smooth performance and dependable protection. Check your vehicle handbook for compatibility.', category: 'Motorcycle', viscosity: 'Semi Synthetic', size: '1000 ml', pricePaisa: 100000, stock: 0, image: '/images/product-semi.webp', featured: true, active: true, specs: { volume: '1000 ml', formulation: 'Semi synthetic' } },
  { id: 'alpha-sn-1200', slug: 'alpha-sn-semi-synthetic-1200ml', name: 'Alpha SN Semi Synthetic', description: 'Engine oil developed for demanding journeys. Select the specification and viscosity recommended for your engine.', category: 'Motorcycle', viscosity: 'SN', size: '1200 ml', pricePaisa: 125000, stock: 0, image: '/images/product-sn.webp', featured: true, active: true, specs: { volume: '1200 ml', formulation: 'Semi synthetic' } },
];

export const fallbackContent = [
  { id: 'hero-1', type: 'HERO', slug: 'engineered-for-your-journey', title: 'Engineered for your journey.', excerpt: 'Performance. Protection. Power. Discover Alpha engine oils for every road ahead.', image: '/images/hero desk 1.jpg', mobileImage: '/images/hero mob img 1.jpg', videoUrl: '/video/hero desk 1.mp4', link: '/products', body: null, youtubeUrl: null, published: true, sortOrder: 0 },
  { id: 'hero-2', type: 'HERO', slug: 'made-for-the-ride', title: 'Made for the ride.', excerpt: 'Your next journey starts here. Find the right Alpha engine oil for your motorcycle.', image: '/images/hero 16 9.jpg', mobileImage: '/images/mob hero 1.jpg', videoUrl: '/video/hero desk 2.mp4', link: '/products?category=Motorcycle', body: null, youtubeUrl: null, published: true, sortOrder: 1 },
  { id: 'hero-3', type: 'HERO', slug: 'precision-power-protection', title: 'Precision power. Uncompromising care.', excerpt: 'High-RPM stability and maximum engine life across Nepal’s roads and mountain terrain.', image: '/images/hero desk 3.jpg', mobileImage: '/images/hero mob img 1.jpg', videoUrl: '/video/hero desk 1.mp4', link: '/products', body: null, youtubeUrl: null, published: true, sortOrder: 2 },
  { id: 'blog-1', type: 'BLOG', slug: 'choosing-engine-oil-nepal', title: 'How to choose engine oil for your motorcycle in Nepal', excerpt: 'Start with your owner’s manual, then understand viscosity, specifications and riding conditions.', body: 'The correct engine oil begins with the requirements in your vehicle owner’s manual. Match the viscosity grade and performance specification before comparing products.\n\nNepal’s changing elevations, stop-start city traffic and longer mountain journeys can create very different operating conditions. Follow the manufacturer’s oil change schedule and have the level checked regularly.\n\nNever select an oil on price alone. Confirm compatibility with your motorcycle’s clutch and engine, buy from a trusted retailer and contact the Alpha team if you need help reading the specification on a bottle.', image: '/images/alpha-racing.webp', youtubeUrl: null, link: null, published: true, sortOrder: 0 },
  { id: 'blog-2', type: 'BLOG', slug: 'motorcycle-oil-level-checks', title: 'A little attention. A better prepared ride.', excerpt: 'Make checking your motorcycle oil level part of a regular care routine.', body: 'Oil level checks are a useful part of looking after your motorcycle. The correct procedure depends on your model: your handbook explains the required engine temperature, waiting time and bike position, as well as how to read the dipstick or sight glass.\n\nKeep the level within the specified range. When topping up, use the oil specified by the manufacturer and add small amounts, checking again as instructed. Do not fill above the maximum mark. A top-up does not replace the scheduled oil and filter service.\n\nIf the oil level falls unexpectedly or you notice a leak, arrange a workshop inspection. Keep a record of your oil changes and ask a qualified technician when you are unsure about the procedure.\n\nFurther reading: Shell, How to do an oil change on a motorcycle: https://www.shell.mu/motorists/motoring-tips-and-advice/how-to-do-an-oil-change-on-a-motorcycle.html', image: '/images/alpha-track.webp', youtubeUrl: null, link: null, published: true, sortOrder: 1 },
  { id: 'blog-3', type: 'BLOG', slug: 'read-motorcycle-oil-label', title: 'Know what goes into your engine.', excerpt: 'Read the oil label alongside your motorcycle handbook before choosing your next bottle.', body: 'An engine oil label contains several pieces of information. The viscosity grade, performance specification, intended application and pack volume each answer a different question. Match all the requirements in your motorcycle handbook; a familiar brand or bottle size is only part of the decision.\n\nFour-stroke motorcycle products may show API and JASO performance information. Check the exact specification required for your motorcycle and its clutch system. A specification printed on one product does not automatically apply to every oil in the same range.\n\nBefore buying, read the current product label, check the seal and confirm how much oil your engine requires. Keep the receipt and maintenance record. If you need help matching a product, bring your motorcycle model and handbook requirements to the Alpha team.\n\nFurther reading: Mobil Super 4T 10W-40 product information explains manufacturer-recommended JASO MA and MA2 applications: https://www.mobil.com/en-cn/passenger-vehicle-lube/pds/ap-xx-mobil-super-4t-10w-40', image: '/images/product-sn.webp', youtubeUrl: null, link: null, published: true, sortOrder: 2 },
  { id: 'gallery-1', type: 'GALLERY', slug: 'alpha-sl-in-focus', title: 'Alpha SL — 800 ml', excerpt: 'A closer look at Alpha SL motorcycle engine oil.', body: null, image: '/images/product-sl-original.jpg', youtubeUrl: null, link: '/products/alpha-sl-800ml', published: true, sortOrder: 0 },
  { id: 'gallery-2', type: 'GALLERY', slug: 'alpha-semi-synthetic-in-focus', title: 'Alpha Semi Synthetic — 1000 ml', excerpt: 'Alpha Semi Synthetic in focus.', body: null, image: '/images/product-semi-original.jpg', youtubeUrl: null, link: '/products/alpha-semi-synthetic-1000ml', published: true, sortOrder: 1 },
  { id: 'gallery-3', type: 'GALLERY', slug: 'alpha-sn-in-focus', title: 'Alpha SN Semi Synthetic — 1200 ml', excerpt: 'Explore the Alpha SN Semi Synthetic pack.', body: null, image: '/images/product-sn-original.jpg', youtubeUrl: null, link: '/products/alpha-sn-semi-synthetic-1200ml', published: true, sortOrder: 2 },
  { id: 'rider-1', type: 'RIDER_PROFILE', slug: 'meengma-53', title: 'Meengma #53', excerpt: 'Built to perform when the ride gets tough. Official Alpha Lubricants rider representing power and precision on the track.', body: 'Power meets the track 🔥🏁 Meet Meengma #53, proudly representing Alpha Lubricants—built to perform when the ride gets tough. 🐺🏍️', image: '/images/rider-meengma.jpg', youtubeUrl: null, link: '/products', published: true, sortOrder: 0 },
  { id: 'rider-2', type: 'RIDER_PROFILE', slug: 'ruby-07', title: 'Ruby #07', excerpt: 'Power meets the track 🔥🏁. Official Alpha Lubricants racer driving high-RPM performance with uncompromising grit.', body: 'Meet Ruby #07, proudly representing Alpha Lubricants on every track and in every condition. Backed by Alpha 20W-50 performance engine oil.', image: '/images/rider-ruby.jpg', youtubeUrl: null, link: '/products', published: true, sortOrder: 1 },
];

export const defaultSettings = { businessName: 'Alpha Lubricants', currency: 'NPR', country: 'NP', shippingPaisa: 15000, freeShippingAbovePaisa: 300000, facebook: 'https://www.facebook.com/profile.php?id=61575309551050', instagram: '', youtube: '', phone: '+977 9801226178', email: 'info@alphalubricant.com', address: 'Tinkune, Kathmandu, Nepal' };
