import Image from 'next/image';
import Link from 'next/link';
import {ArrowUpRight, MessageCircle, Play, Quote} from 'lucide-react';
import {getContent, getSettings, getFeaturedRiders} from '@/lib/server/catalog';
import styles from './cms-sections.module.css';

export type CmsItem = {id:string;title:string;slug:string;excerpt:string|null;body:string|null;image:string|null;link:string|null;youtubeUrl:string|null;videoUrl?:string|null;rating?:number|null;platform?:string|null};
function youtubeId(url:string){try{const u=new URL(url);if(!['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(u.hostname))return null;const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').at(-1);return id&&/^[A-Za-z0-9_-]{11}$/.test(id)?id:null}catch{return null}}
function Photo({item}:{item:CmsItem}){return item.image?<div className={styles.photo}><Image src={item.image} alt={item.title} fill sizes="(max-width:700px) 90vw, (max-width:1000px) 45vw, 30vw" unoptimized={item.image.startsWith('https://')}/></div>:null}
function Heading({title,href,label='View all'}:{title:string;href?:string;label?:string}){return <div className={styles.heading}><h3>{title}</h3>{href&&<Link href={href}>{label}<ArrowUpRight size={20}/></Link>}</div>}
export function VideoCards({items}:{items:CmsItem[]}){return <div className={styles.grid}>{items.map(item=>{const id=item.youtubeUrl?youtubeId(item.youtubeUrl):null;return <article className={styles.card} key={item.id}>{item.videoUrl?<video className={styles.video} controls playsInline preload="none" poster={item.image||undefined}><source src={item.videoUrl}/>Your browser does not support embedded video. <a href={item.videoUrl}>Open video</a></video>:id?<iframe className={styles.video} src={`https://www.youtube-nocookie.com/embed/${id}`} title={item.title} loading="lazy" allow="encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<Photo item={item}/>}<div className={styles.copy}><h4>{item.title}</h4>{item.excerpt&&<p>{item.excerpt}</p>}</div></article>})}</div>}
export function OfferCards({items}:{items:CmsItem[]}){return <div className={styles.grid}>{items.map(item=><article className={styles.card} key={item.id}><Photo item={item}/><div className={styles.copy}><span className={styles.tag}>ALPHA PROMOTION</span><h4>{item.title}</h4><p>{item.excerpt}</p>{item.body&&<p className={styles.body}>{item.body}</p>}{item.link&&<Link className={styles.link} href={item.link}>Learn more <ArrowUpRight size={18}/></Link>}</div></article>)}</div>}
export async function WhatsNew(){const [gallery,videos,social,blogs,settings]=await Promise.all([getContent('GALLERY'),getContent('VIDEO'),getContent('SOCIAL'),getContent('BLOG'),getSettings()]);return <section className={styles.section} id="whats-new"><div className="wrap"><header className={styles.intro}><p className="eyebrow">IN THE WORLD OF ALPHA</p><h2>What's <span>new.</span></h2><p>Our latest moments and stories. All in one place.</p></header><div className={styles.subsection}><Heading title="The gallery" href="/gallery"/>{gallery.length?<div className={styles.grid}>{gallery.slice(0,3).map(item=><Link href="/gallery" className={styles.galleryCard} key={item.id}><Photo item={item}/><h4>{item.title}<ArrowUpRight size={20}/></h4></Link>)}</div>:<p className={styles.empty}>New moments from the Alpha community are on their way.</p>}</div><div className={styles.subsection}><Heading title="Watch Alpha in action" href="/videos"/>{videos.length?<VideoCards items={videos.slice(0,3)}/>:<div className={styles.empty}><Play size={26}/><p>Ride stories and product videos are coming soon.</p></div>}</div><div className={styles.subsection}><Heading title="Follow us on social media" label="Follow Alpha" href={settings.facebook}/><p className={styles.subheading}>Let's stay connected.</p>{social.length?<div className={styles.socialGrid}>{social.slice(0,4).map((item:CmsItem)=><article className={styles.socialCard} key={item.id}><div className={styles.socialAuthor}><Image src="/images/logo.webp" alt="Alpha" width={44} height={44}/><div><strong>Alpha Lubricants</strong><span>{item.platform||item.title}</span></div><MessageCircle size={20}/></div><div className={styles.socialText}><p>{item.excerpt||item.body}</p>{item.link&&<a href={item.link} target="_blank" rel="noreferrer">{item.link.includes('profile.php')?'Visit our page':'Read post'} <ArrowUpRight size={15}/></a>}</div><Photo item={item}/></article>)}</div>:<div className={styles.empty}><p>Follow our official page for the latest from Alpha Lubricants Nepal.</p><a href={settings.facebook} target="_blank" rel="noreferrer">Visit Alpha on Facebook <ArrowUpRight size={18}/></a></div>}</div><div className={styles.subsection}><Heading title="From the Alpha blog" href="/blog"/><div className={styles.grid}>{blogs.slice(0,3).map(item=><article className={styles.card} key={item.id}><Link href={`/blog/${item.slug}`} tabIndex={-1} aria-hidden="true"><Photo item={item}/></Link><div className={styles.copy}><span className={styles.tag}>THE ALPHA JOURNAL</span><h4><Link href={`/blog/${item.slug}`}>{item.title}</Link></h4><p>{item.excerpt}</p><Link className={styles.link} href={`/blog/${item.slug}`}>Read story <ArrowUpRight size={18}/></Link></div></article>)}</div></div></div></section>}
export async function CustomerReviews(){const items=await getContent('REVIEW');return <section className={styles.reviewSection} id="customer-reviews"><div className="wrap"><header className={styles.intro}><p className="eyebrow">THE PEOPLE BEHIND EVERY JOURNEY</p><h2>Customer <span>voices.</span></h2><p>Experiences shared by the Alpha community.</p></header>{items.length?<div className={styles.grid}>{items.map((item:CmsItem)=><figure className={styles.review} key={item.id}><Quote size={32}/>{item.rating&&<p aria-label={`${item.rating} out of 5 stars`} style={{color:"#941c40",letterSpacing:3,marginTop:12}}>{"\u2605".repeat(item.rating)}{"\u2606".repeat(5-item.rating)}</p>}<blockquote>{item.body||item.excerpt}</blockquote><figcaption>{item.image&&<Image src={item.image} alt="" width={52} height={52} unoptimized={item.image.startsWith('https://')}/>}<div><strong>{item.title}</strong>{item.body&&item.excerpt&&<span>{item.excerpt}</span>}</div></figcaption></figure>)}</div>:<div className={styles.empty}><p>Have an Alpha experience to share? We'd love to hear from you.</p><Link href="/contact">Share your experience <ArrowUpRight size={18}/></Link></div>}</div></section>}
export async function RiderProfiles(){const riders=await getFeaturedRiders();return <section className={styles.section}><div className="wrap"><header className={styles.intro}><p className="eyebrow">OFFICIAL ALPHA RIDERS</p><h2>The riders. <span>The stories.</span></h2><p>Power meets the track 🔥🏁 Meet Meengma #53 &amp; Ruby #07, proudly representing Alpha Lubricants—built to perform when the ride gets tough. 🐺🏍️</p></header>{riders.length?<div className={styles.grid}>{riders.map(item=><article className={styles.card} key={item.id}>{item.image?<div className={styles.photo}><Image src={item.image} alt={item.name} fill sizes="(max-width:700px) 90vw, (max-width:1000px) 45vw, 30vw" unoptimized={item.image.startsWith('https://')}/></div>:null}<div className={styles.copy}><h3>{item.name}</h3><p className={styles.body}>{item.bio||'Official Alpha Lubricants rider representing power and protection.'}</p><Link className={styles.link} href="/contact?interest=rider">Join the team <ArrowUpRight size={18}/></Link></div></article>)}</div>:<div className={styles.empty}><p>Meet the Alpha riders here as our community grows.</p><Link href="/contact?interest=rider">Become an Alpha rider <ArrowUpRight size={18}/></Link></div>}</div></section>}

