'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowRight,ArrowUpRight,ChevronLeft,ChevronRight,Pause,Play,Quote,Check,MoveUpRight} from 'lucide-react';
import type { HomeMediaSettings } from '@/lib/server/catalog';
export function Categories({ media }: { media?: HomeMediaSettings }){
  const categories=[
    {name:'Motorcycle',sub:'Made for the ride.',image:media?.categoryMotorcycleImage||'/images/motor cycle.jpg',href:'/products?category=Motorcycle'},
    {name:'Off-road riding',sub:'Beyond the everyday road.',image:media?.categoryOffroadImage||'/images/off roading.jpeg',href:'/products?category=Motorcycle'},
    {name:'Track & Racing',sub:'Born on the circuit. Apex performance.',image:media?.categoryTrackImage||media?.categoryIndustrialImage||'/images/alpha-racing.webp',href:'/products?category=Motorcycle'}
  ];
  const [index,setIndex]=useState(0);
  return <div className="category-section wrap"><div className="category-grid">{[0,1].map(n=>{const item=categories[(index+n)%categories.length];return <Link href={item.href} className="category-card" key={item.name}><div className="category-image"><Image src={item.image} alt={item.name==='Motorcycle'?'Motorcycle riders on a winding road':item.name==='Track & Racing'?'High-speed motorcycle track racing':'Off-road motorcycle rider'} fill sizes="(max-width:700px) 90vw, 43vw"/></div><div className="category-label"><div><h3>{item.name}</h3><p>{item.sub}</p></div><ArrowUpRight size={26}/></div></Link>})}</div><div className="carousel-footer"><span className="micro-label">LUBRICATION FOR YOUR WORLD</span><div className="carousel-line"/><button className="round-button" aria-label="Previous category" onClick={()=>setIndex((index+2)%3)}><ChevronLeft/></button><button className="round-button burgundy" aria-label="Next category" onClick={()=>setIndex((index+1)%3)}><ChevronRight/></button></div></div>}
export function Reveal({children}:{children:React.ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;el.classList.add('reveal-ready');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}})},{threshold:.08});el.querySelectorAll('[data-reveal]').forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);return <div ref={ref}>{children}</div>}
export function Heritage({ media }: { media?: HomeMediaSettings }){
  const values=[
    {label:'Performance',title:'Built around your ride.',text:'From your morning commute to the long way home, the right lubricant helps your engine work at its best. Explore an Alpha oil that matches your vehicle’s requirements.',image:media?.heritagePerformanceImage||'/images/Driven by passion..jpg'},
    {label:'Protection',title:'Care for what drives you.',text:'Regular servicing and the correct engine oil go hand in hand. Our team helps you understand your product options, so your next service starts with an informed choice.',image:media?.heritageProtectionImage||'/images/product-sl.webp'},
    {label:'Power',title:'Keep moving forward.',text:'We share a passion for the ride. Alpha brings together engine care, a growing rider community and a local team in Kathmandu, ready to help.',image:media?.heritagePowerImage||'/images/hero-road.webp'}
  ];
  const [index,setIndex]=useState(0);
  return <section className="heritage wrap" data-reveal><div><p className="eyebrow">THE ALPHA WAY</p><h2>Driven by passion.<br/><span>Defined by care.</span></h2><p>Good journeys begin with what goes into your engine. Get to know the three principles behind Alpha Lubricants.</p><Link className="outline-button" href="/about">Our story <ArrowUpRight size={16}/></Link></div><div><div className="heritage-image"><Image src={values[index].image} alt={values[index].label} fill sizes="(max-width:700px) 90vw, 45vw"/></div><h3>{values[index].title}</h3><p>{values[index].text}</p><div className="heritage-tabs" role="tablist" aria-label="Alpha principles">{values.map((v,i)=><button role="tab" aria-selected={i===index} key={v.label} onClick={()=>setIndex(i)}>{v.label}</button>)}</div></div></section>}
export function TestimonialCards(){return <section className="testimonials wrap" data-reveal><div className="center-heading"><p className="eyebrow">THE PEOPLE BEHIND THE JOURNEYS</p><h2>Your engine.<br className="mobile-only"/> <span>Our commitment.</span></h2><p>Local support. A shared passion for performance.</p></div><div className="promise-grid"><article><Quote size={32}/><h3>Make the right choice</h3><p>Not sure which oil is right for your motorcycle? Tell us your make, model and year. We’ll help you understand the options.</p><Link href="/contact">Talk to the Alpha team <ArrowRight size={18}/></Link></article><article><Check size={30}/><h3>Know what you’re buying</h3><p>Explore original Alpha products, clear pack sizes and transparent prices. Keep your owner’s manual close and your engine’s needs first.</p><Link href="/products">Find your Alpha oil <ArrowRight size={18}/></Link></article></div></section>}
