"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, LogOut, Package, ShoppingBag, UserRound } from "lucide-react";
import { api, dateLabel, money, useSession } from "./session";

type AccountOrder = { id: string; number: string; createdAt: string; status: string; totalPaisa: number; items?: { id?: string; name?: string; productName?: string; quantity: number; product?: { name: string } }[] };
export function AccountDashboard() {
  const { user, loading, error: sessionError } = useSession();
  const [orders, setOrders] = useState<AccountOrder[]>([]);
  const [error, setError] = useState("");
  const [fetching, setFetching] = useState(true);
  const [page, setPage] = useState(1); const [total, setTotal] = useState(0);
  useEffect(() => { if (!user) return; let active = true; setFetching(true); setError(''); api<{ items: AccountOrder[]; total: number }>(`/api/orders?page=${page}&pageSize=10`).then(data => { if (active) { setOrders(data.items); setTotal(data.total); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setFetching(false); }); return () => { active = false; }; }, [user, page]);
  if (loading) return <main className="dash-access"><div className="dash-spinner" /><p>Loading your account…</p></main>;
  if (!user) return <main className="dash-access"><UserRound size={44} /><h1>Your journey with Alpha.</h1><p>Sign in to see your orders and manage your account.</p>{sessionError && <p className="dash-error">{sessionError}</p>}<Link href="/account/login" className="dash-button">Sign in <ArrowRight size={17} /></Link><Link href="/account/register" className="dash-text-link">Create an account</Link></main>;
  async function logout() { try { await api("/api/auth/logout", { method: "POST" }); window.location.href = "/account/login"; } catch (e) { setError((e as Error).message); } }
  return <main className="alpha-account"><div className="dash-page-heading"><div><span className="dash-eyebrow">MY ALPHA</span><h1>Hello, {user.name.split(" ")[0]}.</h1><p>Every order. Every journey. All in one place.</p></div><button className="dash-button secondary" onClick={logout}><LogOut size={16} /> Sign out</button></div><div className="account-grid"><aside className="dash-panel account-profile"><span className="dash-avatar large">{user.name[0]?.toUpperCase()}</span><h2>{user.name}</h2><p>{user.email}</p><div className="account-profile-line"><UserRound size={18} /><span>{user.role === "CUSTOMER" ? "Alpha customer" : user.role.toLowerCase()}</span></div>{user.role === "ADMIN" && <Link className="dash-button" href="/admin">Open admin workspace <ArrowRight size={16} /></Link>}{user.role === "RIDER" && <Link className="dash-button" href="/rider">Open rider workspace <ArrowRight size={16} /></Link>}<Link href="/products" className="dash-text-link">Explore our lubricants <ArrowRight size={16} /></Link></aside><section className="dash-panel"><div className="dash-panel-heading"><div><h2>Your orders</h2><p>Follow the products keeping you moving.</p></div><ShoppingBag size={21} /></div>{error && <div className="dash-error" role="alert">{error}</div>}{fetching ? <div className="dash-empty">Loading your orders…</div> : orders.length === 0 ? <div className="dash-empty"><Package size={38} /><h3>Your next journey starts here.</h3><p>You haven’t placed an order yet.</p><Link href="/products" className="dash-button">Shop lubricants <ArrowRight size={16} /></Link></div> : <div className="account-orders">{orders.map(order => <article key={order.id} className="account-order"><div><strong>#{order.number || order.id.slice(-8).toUpperCase()}</strong><span className={`dash-badge ${order.status.toLowerCase()}`}>{order.status.replaceAll("_", " ")}</span></div><p>{dateLabel(order.createdAt)} <span>·</span> {money(order.totalPaisa / 100)}</p><ul>{order.items?.map((item, index) => <li key={item.id || index}>{item.product?.name || item.productName || item.name || "Product"} <span>× {item.quantity}</span></li>)}</ul></article>)}</div>}{total > 10 && <div className="dash-pagination"><span>{total} orders ? Page {page} of {Math.ceil(total / 10)}</span><div><button className="dash-icon-button" aria-label="Previous orders" disabled={page === 1 || fetching} onClick={() => setPage(page - 1)}><ChevronLeft size={18} /></button><button className="dash-icon-button" aria-label="Next orders" disabled={page * 10 >= total || fetching} onClick={() => setPage(page + 1)}><ChevronRight size={18} /></button></div></div>}</section></div></main>;
}
