"use client";
import { useEffect, useState } from 'react';
import { ArrowDownToLine, ChevronDown, ChevronLeft, ChevronRight, Search, ShoppingBag } from 'lucide-react';
import { api, dateLabel } from './session';
import { downloadCSV, label, Order, orderStatuses, paisa } from './types';

export function OrdersManager({ rider = false }: { rider?: boolean }) {
  const [orders, setOrders] = useState<Order[]>([]); const [riders, setRiders] = useState<{ id: string; name: string }[]>([]); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [busy, setBusy] = useState(true); const [error, setError] = useState(''); const [opened, setOpened] = useState<string | null>(null); const [saving, setSaving] = useState('');
  useEffect(() => { const timeout = setTimeout(() => { setQuery(search); setPage(1); }, 300); return () => clearTimeout(timeout); }, [search]);
  useEffect(() => { let active = true; setBusy(true); setError(''); api<{ items: Order[]; total: number }>(`/api/orders?page=${page}&pageSize=20&status=${status}&q=${encodeURIComponent(query)}`).then(data => { if (active) { setOrders(data.items); setTotal(data.total); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [page, status, query]);
  useEffect(() => { if (!rider) api<{ items: { id: string; name: string }[] }>('/api/admin/riders?pageSize=100').then(data => setRiders(data.items)).catch(e => setError(e.message)); }, [rider]);
  async function update(id: string, values: Record<string, unknown>) { setSaving(id); setError(''); try { const data = await api<{ order: Order }>(`/api/orders/${id}`, { method: 'PATCH', body: JSON.stringify(values) }); setOrders(rows => rows.map(row => row.id === id ? { ...row, ...data.order } : row)); } catch (e) { setError((e as Error).message); } finally { setSaving(''); } }
  return <><div className="dash-page-heading"><div><span className="dash-eyebrow">{rider ? 'DELIVER WITH ALPHA' : 'CUSTOMER JOURNEYS'}</span><h1>{rider ? 'Assigned orders.' : 'Order management.'}</h1><p>{rider ? 'Track the orders and deliveries assigned to your account.' : 'Manage fulfilment, assign your riders and track every order.'}</p></div><button className="dash-button secondary" disabled={!orders.length} onClick={() => downloadCSV('alpha-orders-page.csv', [['Order', 'Date', 'Customer', 'Phone/Email', 'Type', 'Status', 'Promo', 'Total NPR'], ...orders.map(o => [o.number, o.createdAt, o.user?.name || o.guestName || o.shipping?.name || 'Customer', o.guestPhone || o.shipping?.phone || o.user?.email || '', (o.isGuest || !o.user) ? 'Guest' : 'Account', o.status, o.promoCode, o.totalPaisa / 100])])}><ArrowDownToLine size={17} /> Export this page</button></div><section className="dash-panel"><div className="dash-toolbar"><label className="dash-search"><Search size={18} /><input aria-label="Search orders" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search order number or customer..." /></label><label className="dash-filter"><span>Status</span><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{orderStatuses.map(s => <option key={s}>{s}</option>)}</select></label></div>{error && <p role="alert" className="dash-error">{error}</p>}<div className="dash-table-wrap"><table className="dash-table"><thead><tr><th>Order / date</th><th>Customer</th><th>Status</th><th>Rider</th><th>Total</th><th><span className="dash-sr-only">Details</span></th></tr></thead><tbody>{orders.map(order => <OrderRow key={order.id} order={order} rider={rider} riders={riders} saving={saving === order.id} opened={opened === order.id} onOpen={() => setOpened(opened === order.id ? null : order.id)} onUpdate={values => update(order.id, values)} />)}</tbody></table>{busy ? <p className="dash-empty">Loading orders...</p> : !orders.length && <div className="dash-empty"><ShoppingBag size={32} /><h3>No matching orders.</h3><p>Try another search or check back after your first sale.</p></div>}</div><div className="dash-pagination"><span>{total} orders · Page {page} of {Math.max(1, Math.ceil(total / 20))}</span><div><button className="dash-icon-button" aria-label="Previous page" disabled={page === 1 || busy} onClick={() => setPage(page - 1)}><ChevronLeft size={18} /></button><button className="dash-icon-button" aria-label="Next page" disabled={page * 20 >= total || busy} onClick={() => setPage(page + 1)}><ChevronRight size={18} /></button></div></div></section></>;
}
function OrderRow({ order, rider, riders, saving, opened, onOpen, onUpdate }: { order: Order; rider: boolean; riders: { id: string; name: string }[]; saving: boolean; opened: boolean; onOpen: () => void; onUpdate: (values: Record<string, unknown>) => void }) {
  const allowed = order.status === 'PENDING' ? ['PENDING', 'CONFIRMED', 'CANCELLED'] : order.status === 'CONFIRMED' ? ['CONFIRMED', 'PROCESSING', 'CANCELLED'] : order.status === 'PROCESSING' ? ['PROCESSING', 'SHIPPED', 'CANCELLED'] : order.status === 'SHIPPED' ? ['SHIPPED', 'DELIVERED'] : [order.status];
  const isGuest = order.isGuest || !order.user;
  const customerName = order.user?.name || order.guestName || order.shipping?.name || 'Guest customer';
  const contactInfo = isGuest ? (order.guestPhone || order.shipping?.phone || '') : (order.user?.email || order.shipping?.phone || '');
  const deliveryAddress = order.guestAddress || order.shipping?.address || '';
  const deliveryPhone = order.guestPhone || order.shipping?.phone || '';

  return <><tr><td><strong>{order.number}</strong><small>{dateLabel(order.createdAt)}</small></td><td><div style={{display:'flex',alignItems:'center',gap:6,flexWrap:'wrap'}}><strong>{customerName}</strong>{isGuest && <span className="dash-badge" style={{fontSize:10,padding:'1px 5px'}}>Guest</span>}</div><small>{contactInfo}</small></td><td>{rider ? <div className="dash-row-actions"><span className={`dash-badge ${order.status.toLowerCase()}`}>{label(order.status)}</span>{order.status === 'SHIPPED' && <button disabled={saving} className="dash-button secondary" onClick={() => onUpdate({ status: 'DELIVERED' })}>Mark delivered</button>}</div> : <select aria-label={`Status for ${order.number}`} value={order.status} disabled={saving || order.status === 'CANCELLED' || order.status === 'DELIVERED'} onChange={e => onUpdate({ status: e.target.value })}>{allowed.map(s => <option key={s}>{s}</option>)}</select>}</td><td>{rider ? order.rider?.name || 'You' : <select aria-label={`Rider for ${order.number}`} value={order.riderId || ''} disabled={saving} onChange={e => onUpdate({ riderId: e.target.value || null })}><option value="">Unassigned</option>{riders.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select>}</td><td><strong>{paisa(order.totalPaisa)}</strong></td><td><button className="dash-icon-button" aria-label={`Details for ${order.number}`} aria-expanded={opened} onClick={onOpen}><ChevronDown size={17} /></button></td></tr>{opened && <tr className="dash-order-detail"><td colSpan={6}><div><section><h4>Delivery address</h4><p><strong>{customerName}</strong><br />{deliveryAddress}{order.shipping?.city ? <><br />{order.shipping.city}</> : ''}{deliveryPhone ? <><br />Phone: {deliveryPhone}</> : ''}</p>{order.shipping?.notes && <p>Note: {order.shipping.notes}</p>}</section><section><h4>Order items</h4>{order.items?.map(item => <p key={item.id}>{item.name} × {item.quantity} <strong>{paisa(item.unitPricePaisa * item.quantity)}</strong></p>)}{order.promoCode && <p>Promo: <strong>{order.promoCode}</strong></p>}</section></div></td></tr>}</>;
}
