"use client";
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowRight, Boxes, RefreshCw, ShoppingBag, Tag, TrendingUp, Users } from 'lucide-react';
import { api, dateLabel } from './session';
import { downloadCSV, label, Order, paisa } from './types';

type OverviewData = { metrics: { orders: number; revenuePaisa: number; pendingOrders: number; customers: number; products: number; lowStock: number }; recentOrders: Order[]; sales: { date: string; totalPaisa: number; orders: number }[]; statusCounts: { status: string; count: number }[]; promos: { id: string; code: string; type: string; value: number; usedCount: number; active: boolean }[] };
export function Overview({ rider = false }: { rider?: boolean }) {
  const [data, setData] = useState<OverviewData | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(true);
  async function refresh() { setBusy(true); setError(''); try { setData(await api<OverviewData>('/api/dashboard')); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  useEffect(() => { void refresh(); }, []);
  const max = Math.max(...(data?.sales ?? []).map(point => point.totalPaisa), 1);
  const cards = data ? [{ title: rider ? 'Attributed sales' : 'Sales revenue', value: paisa(data.metrics.revenuePaisa), note: 'Delivered orders only', icon: TrendingUp }, { title: 'Total orders', value: data.metrics.orders.toLocaleString(), note: rider ? 'Orders assigned to you' : 'Across your storefront', icon: ShoppingBag }, { title: 'Orders in progress', value: data.metrics.pendingOrders.toLocaleString(), note: 'Awaiting delivery', icon: Boxes }, { title: rider ? 'Promo codes' : 'Customers', value: rider ? data.promos.length : data.metrics.customers, note: rider ? 'Assigned to your account' : 'Registered customer accounts', icon: rider ? Tag : Users }] : [];
  return <><div className="dash-page-heading"><div><span className="dash-eyebrow">{rider ? 'YOUR ALPHA JOURNEY' : 'THE BIG PICTURE'}</span><h1>{rider ? 'Your performance.' : 'Business overview.'}</h1><p>{rider ? 'See your referred sales and the orders assigned to you.' : 'A clear view of your sales, customers and what comes next.'}</p></div><button className="dash-button secondary" disabled={busy} onClick={refresh}><RefreshCw size={16} className={busy ? 'spin' : ''} /> Refresh</button></div>
    {error && <div role="alert" className="dash-error">{error}</div>}{busy && !data && <div className="dash-empty">Loading your business data...</div>}
    {data && <><div className="dash-metrics">{cards.map(card => <article className="dash-metric" key={card.title}><div><span>{card.title}</span><card.icon size={19} /></div><strong>{card.value}</strong><small>{card.note}</small></article>)}</div><div className="dash-overview-grid"><section className="dash-panel"><div className="dash-panel-heading"><div><h2>Sales activity</h2><p>Daily order value · Last 30 days</p></div><button className="dash-icon-button" aria-label="Export sales activity CSV" onClick={() => downloadCSV('alpha-sales.csv', [['Date', 'Orders', 'Sales NPR'], ...data.sales.map(s => [s.date, s.orders, s.totalPaisa / 100])])}><ArrowDownToLine size={19} /></button></div><div className="dash-chart" role="img" aria-label="Daily sales value bar chart. Exact values available in the export.">{data.sales.length ? data.sales.map(point => <div className="dash-chart-column" key={point.date} title={`${dateLabel(point.date)}: ${paisa(point.totalPaisa)} · ${point.orders} orders`}><span style={{ height: `${Math.max(point.totalPaisa / max * 100, point.totalPaisa ? 2 : 0)}%` }} /></div>) : <p>No sales recorded yet.</p>}</div><div className="dash-chart-labels"><span>{dateLabel(data.sales[0]?.date)}</span><span>{dateLabel(data.sales.at(-1)?.date)}</span></div></section><section className="dash-panel"><div className="dash-panel-heading"><div><h2>Order pipeline</h2><p>From checkout to the road.</p></div></div><div className="dash-pipeline">{data.statusCounts.length ? data.statusCounts.map(s => <div key={s.status}><span className={`dash-status-dot ${s.status.toLowerCase()}`} /><span>{label(s.status).toLowerCase()}</span><strong>{s.count}</strong></div>) : <p className="dash-muted">New orders will appear here.</p>}</div>{!rider && <Link className="dash-panel-link" href="/admin/products">{data.metrics.lowStock} products running low <ArrowRight size={16} /></Link>}</section></div>
    <section className="dash-panel"><div className="dash-panel-heading"><div><h2>Recent orders</h2><p>Your latest customer journeys.</p></div>{!rider && <Link className="dash-text-link" href="/admin/orders">View all orders <ArrowRight size={16} /></Link>}</div><div className="dash-table-wrap"><table className="dash-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Status</th><th>Total</th></tr></thead><tbody>{data.recentOrders.map(order => <tr key={order.id}><td><strong>{order.number}</strong></td><td>{order.user?.name || order.shipping?.name || 'Customer'}</td><td>{dateLabel(order.createdAt)}</td><td><span className={`dash-badge ${order.status.toLowerCase()}`}>{label(order.status)}</span></td><td><strong>{paisa(order.totalPaisa)}</strong></td></tr>)}</tbody></table>{!data.recentOrders.length && <div className="dash-empty"><ShoppingBag size={32} /><h3>Ready for your first order.</h3><p>Orders will appear here as customers check out.</p></div>}</div></section>
    {rider && <section className="dash-panel"><div className="dash-panel-heading"><div><h2>Your promo codes</h2><p>Share an active code to attribute customer orders to you.</p></div><Tag size={22} /></div><div className="dash-promo-grid">{data.promos.map(p => <article key={p.id}><span className={`dash-badge ${p.active ? 'delivered' : 'cancelled'}`}>{p.active ? 'Active' : 'Inactive'}</span><h3>{p.code}</h3><p>{p.type === 'PERCENT' ? `${p.value}%` : paisa(p.value)} discount · {p.usedCount} uses</p><button className="dash-button secondary" onClick={async event => { const button = event.currentTarget; try { await navigator.clipboard.writeText(p.code); button.textContent = 'Copied'; } catch { button.textContent = 'Select the code above to copy'; } }}>Copy code</button></article>)}{!data.promos.length && <p className="dash-empty">Your administrator can assign a promo code to your account.</p>}</div></section>}</>}
  </>;
}
