"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { Check, Globe, Save, Truck } from 'lucide-react';
import { api } from './session';
type Settings = { businessName: string; currency: 'NPR'; country: 'NP'; shippingPaisa: number; freeShippingAbovePaisa: number; facebook: string; instagram: string; youtube: string; phone: string; email: string; address: string };
export function SettingsManager() {
  const [settings, setSettings] = useState<Settings | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { api<{ settings: Settings }>('/api/admin/settings').then(data => setSettings(data.settings)).catch(e => setError(e.message)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); setSaved(false); try { const data = Object.fromEntries(new FormData(event.currentTarget)); await api('/api/admin/settings', { method: 'PUT', body: JSON.stringify({ ...data, currency: 'NPR', country: 'NP', shippingPaisa: Math.round(Number(data.shippingPaisa) * 100), freeShippingAbovePaisa: Math.round(Number(data.freeShippingAbovePaisa) * 100) }) }); setSaved(true); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><div className="dash-page-heading"><div><span className="dash-eyebrow">MAKE IT YOURS</span><h1>Store settings.</h1><p>Your business details, social connections and delivery preferences.</p></div></div>{error && <p className="dash-error" role="alert">{error}</p>}{saved && <p className="dash-success" role="status"><Check size={18} />Your settings have been saved.</p>}{settings ? <form onSubmit={submit} className="dash-settings"><section className="dash-panel"><div className="dash-panel-heading"><div><h2>Business information</h2><p>Help customers find and contact Alpha.</p></div><Globe size={22} /></div><div className="dash-form-grid">{[['businessName', 'Business name'], ['email', 'Contact email'], ['phone', 'Contact phone'], ['address', 'Business address']].map(([key, title]) => <label className="dash-field" key={key}>{title}<input name={key} type={key === 'email' ? 'email' : 'text'} required={key === 'businessName'} defaultValue={String(settings[key as keyof Settings])} /></label>)}</div></section><section className="dash-panel"><div className="dash-panel-heading"><div><h2>Social media</h2><p>Connect your community to the channels you use.</p></div></div><div className="dash-form-grid">{['facebook', 'instagram', 'youtube'].map(key => <label className="dash-field" key={key}>{key[0].toUpperCase() + key.slice(1)} URL<input type="url" name={key} placeholder="https://..." defaultValue={String(settings[key as keyof Settings])} /></label>)}</div></section><section className="dash-panel"><div className="dash-panel-heading"><div><h2>Shipping & currency</h2><p>Delivery charges are calculated at checkout.</p></div><Truck size={22} /></div><div className="dash-form-grid"><label className="dash-field">Standard shipping (NPR)<input type="number" name="shippingPaisa" defaultValue={settings.shippingPaisa / 100} min="0" step="0.01" required /></label><label className="dash-field">Free shipping from (NPR)<input type="number" name="freeShippingAbovePaisa" defaultValue={settings.freeShippingAbovePaisa / 100} min="0" step="0.01" required /></label><p className="dash-muted">Store currency: Nepalese rupee (NPR)<br />Delivery country: Nepal</p></div></section><button className="dash-button" disabled={busy}><Save size={17} />{busy ? 'Saving...' : 'Save settings'}</button></form> : !error && <div className="dash-empty">Loading settings...</div>}</>;
}
