'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Droplets, ArrowUpRight } from 'lucide-react';
import type { VehicleEntry } from '@/lib/vehicle-seeds';
import styles from './finder.module.css';
export function OilFinder({vehicles}:{vehicles:VehicleEntry[]}) {
 const [make,setMake]=useState('');const [model,setModel]=useState('');const [variant,setVariant]=useState('');const [shown,setShown]=useState(false);
 const models=vehicles.filter(v=>v.make===make);const variants=models.filter(v=>v.model===model);const result=variants.find(v=>v.variant===variant);
 return <section className={styles.wrap} id="oil-finder"><div className={styles.heading}><span className={styles.eyebrow}><Droplets size={20}/> YOUR ENGINE. THE RIGHT OIL.</span><h1>Find the oil<br/><em>for your journey.</em></h1><p>Select your vehicle to see its oil requirements and available Alpha matches. No login needed.</p></div><div className={styles.panel}><form onSubmit={e=>{e.preventDefault();setShown(true)}}><div className={styles.fields}><label>Vehicle brand<select required value={make} onChange={e=>{setMake(e.target.value);setModel('');setVariant('');setShown(false)}}><option value="">Choose brand</option>{[...new Set(vehicles.map(v=>v.make))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Model<select required disabled={!make} value={model} onChange={e=>{setModel(e.target.value);setVariant('');setShown(false)}}><option value="">Choose model</option>{[...new Set(models.map(v=>v.model))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Variant / handbook edition<select required disabled={!model} value={variant} onChange={e=>{setVariant(e.target.value);setShown(false)}}><option value="">Choose variant</option>{variants.map(v=><option key={v.variant}>{v.variant}</option>)}</select></label></div><button className={styles.button}>Find my oil <ArrowUpRight size={20}/></button></form>{shown&&result&&<div className={styles.result} aria-live="polite"><span className={styles.eyebrow}>{result.status==='VERIFIED'?'HANDBOOK SPECIFICATION MATCH':'MATCH AWAITING CONFIRMATION'}</span><h2>{result.make} {result.model}</h2><p>{result.variant}</p>{result.viscosity&&<p className={styles.spec}>{result.viscosity} / {result.specification}</p>}<p>{result.notes}</p>{result.status==='VERIFIED'&&result.productSlug?<Link className={styles.button} href={`/products/${result.productSlug}`}>View matching Alpha oil <ArrowUpRight size={18}/></Link>:<Link className={styles.button} href="/contact">Ask Alpha for help <ArrowUpRight size={18}/></Link>}<div className={styles.sources}><a href={result.marketSource} target="_blank" rel="noreferrer">Nepal vehicle source â†—</a>{result.manualSource&&<a href={result.manualSource} target="_blank" rel="noreferrer">Manufacturer handbook â†—</a>}</div></div>}<p className={styles.hint}>Cannot find your exact year or variant? <Link href="/contact">Contact our team</Link> with the engine details from your handbook.</p></div></section>
}

