'use client';
import { useEffect,useState } from 'react';
import type { VehicleEntry } from '@/lib/vehicle-seeds';
import styles from './finder.module.css';
type Product={slug:string;name:string;viscosity:string};
const blank:VehicleEntry={make:'',model:'',variant:'',category:'Motorcycle',marketSource:'',manualSource:'',viscosity:'',specification:'',productSlug:'',status:'PENDING',notes:'',active:true};
export function VehicleManager(){const [items,setItems]=useState<VehicleEntry[]>([]);const [products,setProducts]=useState<Product[]>([]);const [form,setForm]=useState<VehicleEntry>({...blank});const [editing,setEditing]=useState(false);const [q,setQ]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
async function load(){try{const r=await fetch('/api/admin/oil-finder');const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);setProducts(d.products)}catch(e){setStatus(e instanceof Error?e.message:'Unable to load vehicles.')}}useEffect(()=>{void load()},[]);
function change(key:keyof VehicleEntry,value:string|boolean){setForm(f=>({...f,[key]:value}))}
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setStatus('');try{const r=await fetch('/api/admin/oil-finder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.issues?JSON.stringify(d.issues.fieldErrors):d.error);setEditing(false);setStatus('Vehicle mapping saved.');await load()}catch(e){setStatus(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
return <div className={styles.admin}><h1>Vehicle oil finder</h1><p>Manage public vehicle records and handbook-specific oil matches. Pending records never recommend a product.</p><button className={styles.button} onClick={()=>{setForm({...blank});setEditing(true)}}>Add vehicle</button>{status&&<div role="status" className={styles.message}>{status}</div>}{editing&&<form onSubmit={save}><h2 className={styles.full}>{form.id?'Edit vehicle':'New vehicle'}</h2>{([['make','Brand'],['model','Model'],['variant','Variant / model year / handbook edition'],['category','Vehicle category'],['marketSource','Nepal manufacturer / distributor source URL'],['manualSource','Exact manufacturer handbook URL'],['viscosity','Required viscosity'],['specification','Required API / JASO / OEM specification']] as const).map(([key,label])=><label key={key}>{label}<input required={['make','model','variant','category','marketSource'].includes(key)} type={key.endsWith('Source')?'url':'text'} value={form[key]||''} onChange={e=>change(key,e.target.value)}/></label>)}<label>Matching Alpha product<select value={form.productSlug||''} onChange={e=>change('productSlug',e.target.value)}><option value="">No published match</option>{products.map(p=><option key={p.slug} value={p.slug}>{p.name} — {p.viscosity}</option>)}</select></label><label>Review status<select value={form.status} onChange={e=>change('status',e.target.value)}><option value="PENDING">Pending handbook review</option><option value="VERIFIED">Verified specification match</option></select></label><label className={styles.full}>Customer guidance / compatibility limits<textarea required minLength={10} value={form.notes} onChange={e=>change('notes',e.target.value)}/></label><label><span><input type="checkbox" checked={form.active} onChange={e=>change('active',e.target.checked)}/> Visible in public finder</span></label><div className={styles.full}><button disabled={busy} className={styles.button}>{busy?'Saving…':'Save mapping'}</button> <button type="button" onClick={()=>setEditing(false)}>Cancel</button></div></form>}<div style={{marginTop:30}}><label>Search vehicles <input value={q} placeholder="Brand, model, variant…" onChange={e=>setQ(e.target.value)}/></label><p>{items.length} records · {items.filter(i=>i.status==='VERIFIED').length} verified matches</p></div><div className={styles.adminList}>{items.filter(v=>`${v.make} ${v.model} ${v.variant}`.toLowerCase().includes(q.toLowerCase())).map(v=><div key={v.id} className={styles.adminRow}><div><strong>{v.make} {v.model}</strong><br/><small>{v.variant} · {v.status==='VERIFIED'?'Verified':'Pending review'}{!v.active?' · Hidden':''}</small></div><button onClick={()=>{setForm(v);setEditing(true);window.scrollTo({top:0,behavior:'smooth'})}}>Edit mapping</button></div>)}</div></div>
}
